Fix org.freedesktop.Accounts.User.SetPassword
canonical/ubuntu-desktop-provision pull request #122
Opened 2023-09-13 14:59 UTC by sergio-costas

The method org.freedesktop.Accounts.User.SetPassword expects a crypted password as its first parameter. Unfortunately, the current code is sending the password in plain text. That plain text password is being stored as-is in the 'shadow' file, and that prevents ubuntu-core-desktop-init to work on core desktop, because the created user has an invalid password field.

This patch fixes it.

2023-09-13 16:18 UTC, kenvandine approved these changes
This looks good to me

2023-09-13 17:41 UTC, d-loose approved these changes
Had a few minutes to look at this, should be good to go now :)
Thanks @sergio-costas!

@tim-hm please have a quick look - I had to update the pubspec.lock, which is checked into the repo here. Feel free to merge if you don't have any objections.

2023-09-15 15:05 UTC, tim-hm requested changes

2023-09-15 15:17 UTC, tim-hm commented on pubspec.lock
> +  flutter: ">=3.10.6"
Oh wait ... these values are correct! My confusion apologies!

2023-09-15 15:17 UTC, tim-hm approved these changes

2023-09-15 15:19 UTC, tim-hm requested changes
@sergio-costas two changes please:

1. could you update your commit messages to follow the convention commit style?
2. can you rebase against dev as I've pushed a handful of commits

Thanks!

2023-09-15 15:19 UTC, sergio-costas commented on pubspec.lock
> +  flutter: ">=3.10.6"
I rebased it, but I still see the same...

2023-09-15 15:28 UTC, merged