WIP: feat: add provd identity service
canonical/ubuntu-desktop-provision pull request #292
Opened 2024-01-03 16:17 UTC by d-loose

Replaces the DBus-based XDG identity service with one based on provd.

Some things that need to be figured out:

- We probably don't want to create a user account immediately after the user presses 'next' on the identity page. Either we have to maintain a state in provd like subiquity does (in that case we should use similar methods, e.g. `setIdentity` instead of `createUser` and add an `apply` method that carries out the user creation) , or we need to handle this in the UI and keep a state in the client.
- Depending on how we want to handle the previous point, we might not need a `getUser` method in provd. It's supposed to return the ephemeral user account information configured in the UI before the account is created.

2024-01-03 16:21 UTC, d-loose commented on packages/provd_client/lib/src/provd_user_client.dart
> +    } on GrpcError catch (_) {
So far provd only returns a boolean here and propagates additional information (i.e. why the username is invalid) as grpc errors. We could either generalize the grpc response (similar to how subiquity does this) or handle the different grpc error cases (once defined) here in the client and then wrap the result in an enum again.

2024-01-03 16:24 UTC, d-loose commented on packages/ubuntu_init/lib/src/services/provd_identity_service.dart
> +  }
See comment at the beginning. If we want to maintain a state here, we should call `apply` separately at a later point after which we can't return to the identity page in the UI.

2024-01-04 16:19 UTC, d-loose commented
> We probably don't want to create a user account immediately after the user presses 'next' on the identity page. ...

Update: After some discussions about the first boot initialization step we could consider making the user creation irreversible, i.e. actually create the account when the user presses 'next' and remove the 'back' button on the following page.

Advanced users (especially those setting up a managed/enterprise machine) might want to open a terminal and perform actions using the new local user right away (while ubuntu-init is still running).

2024-01-10 08:23 UTC, d-loose commented on packages/provd_client/lib/src/provd_user_client.dart
> +    } on GrpcError catch (_) {
We decided to return an enum from the backend instead

2024-01-16 15:57 UTC, d-loose commented on packages/provd_client/lib/src/generated/accessibility.pb.dart
Oh, didn't mean to delete all those ... Will restore them

2024-01-18 12:05 UTC, matthew-hagemann requested changes
Hi Dennis,

I've run into a few issues with username validation in the new setup:

I am able to create a user from the reserved list (ie: root)
It looks like `provd` does fail, because if I click next, `ubuntu_init` gets stuck

![Screenshot from 2024-01-18 12-27-47](https://github.com/canonical/ubuntu-desktop-provision/assets/93575731/22042052-30d0-4975-af03-b80829f131cd)

Same issue for other reserved usernames. I also tried `gdm`

I also ran into an issue where valid usernames were rejected as being taken:

![Screenshot from 2024-01-18 13-31-59](https://github.com/canonical/ubuntu-desktop-provision/assets/93575731/a47288f5-3344-4f00-9723-a426b413363e)

If it would be helpful, I can add some debug-logs to `provd` and push a new version up to help inspect.

2024-01-18 13:56 UTC, d-loose commented
Do you have the logs from ubuntu_init? I can't reproduce it so far.

2024-01-19 11:39 UTC, matthew-hagemann approved these changes
LGTM!

2024-01-19 12:34 UTC, d-loose commented
I assume all the issues you encountered were due to bugs in provd and/or your testing setup then?
In any case I'll only merge this once we're happy with the backend side :)

2024-01-19 13:09 UTC, matthew-hagemann commented
@d-loose Yea, I can't reproduce any of my issues after redoing my test infrastructure :slightly_smiling_face:
Cool beans! I'll send a PR out in a bit, just making some last changes for Didier :+1:

2024-01-31 11:22 UTC, merged